# To log execution times of time critical operations
log_times: False

# Return messages to the terminal that are relevant for debugging
debug_mode: True

# Lookahead for motion update
lookahead: 2.5

robot_diameter: 0.45

# Min and max velocity values of the rto (Unit: m/s, rad/s)
min_linear_vel: 0 # think about negative values 
max_linear_vel: 0.2
min_angular_vel: -0.7 #changed for testing purpose
max_angular_vel: 0.7

# Max acceleration and deceleration that can be achieved by the rto (Unit: m/s^2 / rad/s^2)
max_acc: 0.3 # Since resolution of global path is 0.05 m => at 10 Hz we can drive a max of  3 cm if robot standing still. 
max_dec: 0.4

# Number of sampled trajectories 
res_ang_vel_space: 10
res_lin_vel_space: 10

# Gain for calculation of cost function for each trajectory
gain_vel: 20
gain_goal_angle: 2
gain_glob_path: 10
gain_clearance: 20

# versions:
# v1: 20 10 100 0 -> follows path good, but sometimes local minima (rotate to goal and no lin vel)
# v2: 50 10 100 0 -> no local minima but makes too big turn radius (not thoroughly tested)
# v3: 20 1  80  0 -> seems to have np local minima, relative decent turning radius and relative constant lin vel (best so far, not thoroughly tested)
# v4: 20 2  80  0
# v5: 20 2  80  20 -> seems to work normal. Robot does not crash any obstacles, but avoidance in not working (just stays)
# v6: 20 2  40  20 -> does not stay on path as much and avoidance is still not working
# v6: 20 2  10  20 -> obstacle avoidance seems to work quite well, but robot is too off of path most at time and not very 'goal driven'

# Distance from goal that is enough to declare goal reached
min_dist_goal: 0.2