# To log execution times of time critical operations
log_times: False

# Return messages to the terminal that are relevant for debugging
debug_mode: True

# Use the pose of the odometry message for position estimation
odometry_pose: True

# Lookahead for motion update
lookahead: 2.5

# Min and max velocity values of the rto (Unit: m/s, rad/s)
min_linear_vel: 0
max_linear_vel: 0.2
min_angular_vel: -0.3 #changed for testing purpose
max_angular_vel: 0.3

# Max acceleration that can be achieved by the rto (Unit: m/s^2 / rad/s^2)
max_acc: 0.3 # Since resolution of global path is 0.05 m => at 10 Hz we can drive a max of  3 cm if robot standing still. 

# Number of sampled trajectories 
res_ang_vel_space: 10
res_lin_vel_space: 10

# Gain for calculation of cost function for each trajectory
gain_vel: 20
gain_goal_angle: 10
gain_glob_path: 100
gain_clearance: 0

# Match_orientation, etc.
min_dist_goal: 0.2