# Min and max velocity values of the rto (Unit: m/s, rad/s)
min_linear_vel: 0
max_linear_vel: 1
min_angular_vel: -1 #changed for testing purpose
max_angular_vel: 1

# Max acceleration that can be achieved by the rto (Unit: m/s^2 / rad/s^2)
max_acc: 0.5

# Number of sampled trajectories 
res_ang_vel_space: 10
res_lin_vel_space: 10

# Gain for calculation of cost function for each trajectory
gain_vel: 1
gain_goal_angle: 1
gain_glob_path: 1
gain_clearance: 0

# Match_orientation, max_dist_to_goal, costs, etc.