# Min and max velocity values of the rto (Unit: m/s, rad/s)
min_linear_vel: 0
max_linear_vel: 1
min_angular_vel: -0.3
max_angular_vel: 0.3

# Max acceleration that can be achieved by the rto (Unit: m/s^2)
max_acc: 0.5

# Number of sampled trajectories 
res_ang_vel_space: 100
res_lin_vel_space: 100

# Match_orientation, max_dist_to_goal, costs, etc.