dynamics_translation_noise_std_dev: 0.3
dynamics_orientation_noise_std_dev: 0.01
num_particles: 200
num_beams: 30
update_rate: 10 # defines rate of prediction and update --> rate=20Hz/update_rate
odom_noise: False # True, False
launch_style: init # init,random (random just works with 400 particles, but with this big number of 				   computational cost in localization is high)
localization_error: 4.5
localization_error_percentage: 0.25
