# Map to start the costmap generator with.
init_map_nr: 1

# To log execution times of time critical operations
log_times: True

# Return messages to the terminal that are relevant for debugging
debug_mode: False

# Params necessary for padding of obstacles to obatain a point representation 
# of the robot for the task of path planning.
global_costmap: {
  robot_diameter: 0.45,
  safety_distance: 0.1,
  padded_val: 99,
  apply_soft_padding: True,
  decay_distance: 0.2,
  decay_type: exponential # linear, exponential, reciprocal
}

# Params necessary for the generation of the local_costmap, which is needed by the
# local planner to avoid appearing obstacles.
local_costmap: {
  length: 3,
  frequency: 10,
  frequency_scan: 40
}
