# Map to start the costmap generator with.
init_map_nr: 1

# Params necessary for padding of obstacles to obatain a point representation 
# of the robot for the task of path planning.
global_costmap: {
  robot_diameter: 0.45,
  safety_distance: 0.2,
  cost_decay: [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]
  #decay_type: quadratic, logarithmic, etc
}
